[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "api-collector"
version = "0.1.0"
description = "Asynchronous Source Interrogator"
requires-python = ">=3.14"
dependencies = ["requests"]
[project.optional-dependencies]
dev = ["mypy", "ruff", "pytest"]

[project.scripts]
api-collector = "api_collector.main:main"

[tool.mypy]
strict = true
files = ["api_collector", "tests"]

[tool.ruff]
target-version = 'py314'
src = ["api_collector"]
line-length = 88

[tool.ruff.lint]
select = ["F", "E", "W", "I"]

[tool.ruff.lint.isort]
known-first-party = ["api_collector"]

[tool.pytest.ini_options]
minversion = "9.0"
addopts = "-v --showlocals --import-mode=importlib"
testpaths = ["tests"]
